version: '3'

services:

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: my-rabbitmq
    hostname: localhost-rabbit
    command: >
      bash -c "
       apt-get update -y &&
       apt-get install -y wget &&
       wget https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.12.0/rabbitmq_delayed_message_exchange-3.12.0.ez &&
       mv rabbitmq_delayed_message_exchange-3.12.0.ez $RABBITMQ_HOME/plugins/ &&
       rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange &&
       rabbitmq-server
      "
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo
    container_name: mongodb
    hostname: localhost-mongo
    ports:
      - "27017:27017"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-app:latest
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - rabbitmq